import { ISeedCategory, IUser } from "@/interfaces"
import bcryptjs from 'bcryptjs'


interface ISeedData {
    users: IUser[],
    categories: ISeedCategory[]
}

export const initialData: ISeedData = {
    users: [
        {
            name: 'Sebastian Narvaez',
            email: 'sebasnarvaez@gmail.com',
            password: bcryptjs.hashSync('123456'),
            status: true
        },
        {
            name: 'Gabriela Sierra',
            email: 'gabi@gmail.com',
            password: bcryptjs.hashSync('123456'),
            status: true
        }
    ],
    categories: [
        {
            _id: '1',
            name: 'Verbos Regulares',
            icon: '📚',
            words: [
                { english: "divide", spanish: "dividir", points: 0, image: "https://i.giphy.com/media/6PDD11h741IpG/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "support", spanish: "soportar", points: 0, image: "https://i.giphy.com/media/ew8hN0QnkoaOdTn2Eo/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "follow", spanish: "seguir", points: 0, image: "https://i.giphy.com/media/TisFptjsMKzYp1fAzo/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "complete", spanish: "completar", points: 0, image: "https://i.giphy.com/media/Q5RiiXiUWWVjvE3rER/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "suck", spanish: "chupar", points: 0, image: "https://i.giphy.com/media/FnxHqXpcyYN32/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "pull", spanish: "halar - tirar de", points: 0, image: "https://i.giphy.com/media/SsIZAm4IDC6yUQMa45/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "practice", spanish: "practicar", points: 0, image: "https://i.giphy.com/media/xT9DPjkNXsQuoZva6c/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "lower", spanish: "bajar - reducir - disminuir", points: 0, image: "https://i.giphy.com/media/g8tLOZ6RWlDvRf5Kfp/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "kiss", spanish: "besar", points: 0, image: "https://i.giphy.com/media/l2Je2M4Nfrit0L7sQ/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "wed", spanish: "casar(se) - unirse con", points: 0, image: "https://i.giphy.com/media/urgh3QkW9wgG8goYCQ/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "smile", spanish: "sonreir", points: 0, image: "https://i.giphy.com/media/QTrG6mjkHEkpFR3DqX/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "fish", spanish: "pescar", points: 0, image: "https://i.giphy.com/media/Xy0VPXTENJyG2HFqtr/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "rest", spanish: "descansar - reposar", points: 0, image: "https://i.giphy.com/media/fdlcvptCs4qsM/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "warm", spanish: "calentar(se) - recalentar", points: 0, image: "https://i.giphy.com/media/3o6Zt2FsmthIOdUm5y/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "visit", spanish: "visitar - hacer visitas", points: 0, image: "https://i.giphy.com/media/3o6ZtaDUO4wr2LJCqk/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "descend", spanish: "descender - bajar", points: 0, image: "https://i.giphy.com/media/11nPtzt27joQQ8/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "add", spanish: "añadir - sumar", points: 0, image: "https://i.giphy.com/media/3o6MbmXIt1qUsNzfu8/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "taste", spanish: "saborear - catar - probar", points: 0, image: "https://i.giphy.com/media/l2Sq0ogljPAubE2nS/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "ski", spanish: "esquiar", points: 0, image: "https://i.giphy.com/media/l0HlUVUnpHH36zoek/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "flee", spanish: "evitar - huir de", points: 0, image: "https://i.giphy.com/media/S3PjeN6iPYyxJYvdji/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "look", spanish: "mirar - fijar mirada en algo", points: 0, image: "https://i.giphy.com/media/kd9BlRovbPOykLBMqX/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "shout", spanish: "gritar", points: 0, image: "https://i.giphy.com/media/IVT4vN0Ywp93aeKSzd/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "decide", spanish: "decidir", points: 0, image: "https://i.giphy.com/media/xUA7aUNw61j9Vdzs0U/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "disagree", spanish: "discrepar - no estar de acuerdo", points: 0, image: "https://i.giphy.com/media/l0HlFq5c61LraxYaI/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "pack", spanish: "empacar - envasar", points: 0, image: "https://i.giphy.com/media/M8vBiv9mgpHDGpqL9y/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "seem", spanish: "parecer", points: 0, image: "https://i.giphy.com/media/rVeJCzA8bCQUk4JQ4v/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "offer", spanish: "ofrecer", points: 0, image: "https://i.giphy.com/media/l2QEdZMha3XrvypMY/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "circle", spanish: "rodear - hacer un circulo", points: 0, image: "https://i.giphy.com/media/OtP2Jj6IuVbhu/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "climb", spanish: "subir - trepar - escalar", points: 0, image: "https://i.giphy.com/media/kfLIA5rPSEdYrGvWLw/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "play", spanish: "jugar - tocar - reproducir", points: 0, image: "https://i.giphy.com/media/YgsGYbakNrZg3sVmop/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "vanish", spanish: "desvanecer(se) - desaparecer", points: 0, image: "https://i.giphy.com/media/kelU5SPX69mnvlKts2/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "destroy", spanish: "destruir", points: 0, image: "https://i.giphy.com/media/10UHehEC098kAE/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "squeeze", spanish: "apretar", points: 0, image: "https://i.giphy.com/media/TLIed7IwyosvDnXZLD/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "grate", spanish: "rallar - raspar", points: 0, image: "https://i.giphy.com/media/co4PLMN4BYHdC4ZPuW/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "cool", spanish: "enfriar - refrescar(se) -  calmar(se)", points: 0, image: "https://i.giphy.com/media/mGK0QLlJtLkzIx43PI/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "spoil", spanish: "estropear - echar a perder - mimar", points: 0, image: "https://i.giphy.com/media/9mEPFPEwBA0JlDvYlQ/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "carry", spanish: "llevar", points: 0, image: "https://i.giphy.com/media/dXA0rJGesbvFHn3RkP/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "dream", spanish: "soñar", points: 0, image: "https://i.giphy.com/media/3o8doTrOWoQMV8h74k/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "work", spanish: "trabajar - funcionar", points: 0, image: "https://i.giphy.com/media/13rQ7rrTrvZXlm/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "punish", spanish: "castigar", points: 0, image: "https://i.giphy.com/media/pRotk2UQTsozm/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "paint", spanish: "pintar", points: 0, image: "https://i.giphy.com/media/hQu3aAkP2I0bn3k1hl/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "talk", spanish: "hablar - conversar", points: 0, image: "https://i.giphy.com/media/M8xmO5ZcLPtAY/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "peel", spanish: "pelar", points: 0, image: "https://i.giphy.com/media/p3P5xLjTI2iu13ronY/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "underline", spanish: "subrayar", points: 0, image: "https://i.giphy.com/media/KBDGEAI1JHIftkUhjD/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "discover", spanish: "descubrir", points: 0, image: "https://i.giphy.com/media/0IGsC1JY4k0LzdDJfb/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "check", spanish: "comprobar -  chequear -  verificar", points: 0, image: "https://i.giphy.com/media/kLOkqcrdC5mrCE7k7G/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "stay", spanish: "permanecer - quedarse - durar", points: 0, image: "https://i.giphy.com/media/TGUIq0O5s4XJSnefJ3/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "cheer", spanish: "victorear -  alegrar -  animar -  aplaudir", points: 0, image: "https://i.giphy.com/media/11sBLVxNs7v6WA/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "speed", spanish: "acelerar - apresurarse - darse prisa", points: 0, image: "https://i.giphy.com/media/qxM03tz9rg4RYThmkG/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "count", spanish: "contar", points: 0, image: "https://i.giphy.com/media/xUPGcqaVH1cDeKZTBS/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "laugh", spanish: "reir(se)", points: 0, image: "https://i.giphy.com/media/CoDp6NnSmItoY/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "mop", spanish: "trapear - fregar", points: 0, image: "https://i.giphy.com/media/l2YWkhCvZ2ufDVar6/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "cancel", spanish: "cancelar", points: 0, image: "https://i.giphy.com/media/l4FGlqf3GnH6mXY08/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "pronounce", spanish: "pronunciar", points: 0, image: "https://i.giphy.com/media/l2JdZtmjxPJ2M1d9C/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "describe", spanish: "describir", points: 0, image: "https://i.giphy.com/media/STLj8QUhg25pe/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "listen", spanish: "escuchar", points: 0, image: "https://i.giphy.com/media/4oMoIbIQrvCjm/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "fill", spanish: "llenar - rellenar", points: 0, image: "https://i.giphy.com/media/xT9IgFQsNYi1zBUiyc/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "discuss", spanish: "discutir", points: 0, image: "https://i.giphy.com/media/kSacoMuLSoNTfInwsB/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "splash", spanish: "salpicar - rociar", points: 0, image: "https://i.giphy.com/media/iNZffK78WQ0LF3ZWLb/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "inspect", spanish: "inspeccionar", points: 0, image: "https://i.giphy.com/media/jFhWlcjuUkEacx4ZCU/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "help", spanish: "ayudar - socorrer", points: 0, image: "https://i.giphy.com/media/l0Extn1wgzXyZn0J2/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "order", spanish: "ordenar - disponer", points: 0, image: "https://i.giphy.com/media/03xd6iUVUOSgSMupzO/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "assign", spanish: "asignar", points: 0, image: "https://i.giphy.com/media/l2SpQlNVrKuypajWE/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "plan", spanish: "planear", points: 0, image: "https://i.giphy.com/media/yv1ggi3Cbase05a8iS/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "move", spanish: "mover - trastear", points: 0, image: "https://i.giphy.com/media/3F1pInHV8vz5HXfAzM/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "remember", spanish: "recordar -  acordarse", points: 0, image: "https://i.giphy.com/media/3orieTQUh6WCMckclq/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "wait", spanish: "esperar", points: 0, image: "https://i.giphy.com/media/l0HlBO7eyXzSZkJri/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "enjoy", spanish: "gozar(de) - disfrutar disfrutar", points: 0, image: "https://i.giphy.com/media/ifM0rVliHWXfsEEQOS/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "believe", spanish: "creer", points: 0, image: "https://i.giphy.com/media/3o6wrGqTd5HbwPJkYw/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "share", spanish: "compartir", points: 0, image: "https://i.giphy.com/media/1oFqxMYv5JQvuFtX8o/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "watch", spanish: "observar - velar - vigilar", points: 0, image: "https://i.giphy.com/media/n6Gk6pAMeP9NS/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "lead", spanish: "conducir - liderar", points: 0, image: "https://i.giphy.com/media/3orif4BtRvTgRedJF6/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "wash", spanish: "lavar - fregar - mojar", points: 0, image: "https://i.giphy.com/media/oM8CvBlVubezC/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "calm", spanish: "calmar", points: 0, image: "https://i.giphy.com/media/2ilegKh8fMdJAVqbG2/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "copy", spanish: "copiar", points: 0, image: "https://i.giphy.com/media/FZPBHxQbXbOUUB69Q7/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "attach", spanish: "unir - juntar - sujetar - pegar", points: 0, image: "https://i.giphy.com/media/Y1dzeiMAHY3ohSFPZC/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "worry", spanish: "preocupar", points: 0, image: "https://i.giphy.com/media/14oABfwMhnvZfi/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "award", spanish: "otorgar", points: 0, image: "https://i.giphy.com/media/CMVMPGhA7yHdYxo7Xf/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "like", spanish: "gustar - querer", points: 0, image: "https://i.giphy.com/media/l0IyccEqUTO7xy9Ec/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "dance", spanish: "bailar", points: 0, image: "https://i.giphy.com/media/EFgksQHxImgta/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "excuse", spanish: "excusar", points: 0, image: "https://i.giphy.com/media/SY44A3CMBwM83yI7t2/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "place", spanish: "poner - colocar - situar", points: 0, image: "https://i.giphy.com/media/hSjSZkQtCHdAbgEZPc/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "sprinkle", spanish: "rociar", points: 0, image: "https://i.giphy.com/media/l4Jz3a8jO92crUlWM/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "celebrate", spanish: "celebrar", points: 0, image: "https://i.giphy.com/media/jcwDyr6UBjLebH863a/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "assist", spanish: "asistir - ayudar ", points: 0, image: "https://i.giphy.com/media/kD4pknHevDUQNOTSbl/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "mix", spanish: "mezclar - barajar", points: 0, image: "https://i.giphy.com/media/1X7qz2KCFnU0Il8RSk/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "defend", spanish: "defender", points: 0, image: "https://i.giphy.com/media/nG9tIH9H7CAk9sEDfu/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "sharpen", spanish: "afilar - ampliar", points: 0, image: "https://i.giphy.com/media/7SoghL1WjxTK9CkkpS/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "blush", spanish: "sonrojar", points: 0, image: "https://i.giphy.com/media/rpf0Du8NasK6Q/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "attend", spanish: "atender", points: 0, image: "https://i.giphy.com/media/6MpYHxuYBaRcD9eF4L/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "type", spanish: "mecanografiar - digitar", points: 0, image: "https://i.giphy.com/media/3o7aCTfyhYawdOXcFW/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "clap", spanish: "aplaudir", points: 0, image: "https://i.giphy.com/media/1236TCtX5dsGEo/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "fade", spanish: "desteñir - desvanecer(se)", points: 0, image: "https://i.giphy.com/media/d8P7zL3QrEotHWPRrR/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "learn", spanish: "aprender", points: 0, image: "https://i.giphy.com/media/qKltgF7Aw515K/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "chill", spanish: "resfriar", points: 0, image: "https://i.giphy.com/media/5hxsG54XihuvDNsrCB/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "open", spanish: "abrir", points: 0, image: "https://i.giphy.com/media/jyPWfqzhit2HEBDymN/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "prefer", spanish: "preferir", points: 0, image: "https://i.giphy.com/media/HrFiaDpS7mP1XzJiZZ/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "use", spanish: "usar", points: 0, image: "https://i.giphy.com/media/mgJHCuKiCy5KU/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "notice", spanish: "notar - advertir", points: 0, image: "https://i.giphy.com/media/VPevIZhmlNOms/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "jog", spanish: "trotar", points: 0, image: "https://i.giphy.com/media/CXLdpFUp9zsoaw3X8c/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "grade", spanish: "graduar - calificar - clasificar", points: 0, image: "https://i.giphy.com/media/iH1rdIKYvNhOu5Z8RY/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "demostrate", spanish: "demostrar", points: 0, image: "https://i.giphy.com/media/l1Kdb3gWBSzFgVIek/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "enroll", spanish: "inscribirse - matricular", points: 0, image: "https://i.giphy.com/media/oyGpShr0FL7Fmdu1CG/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "stop", spanish: "parar - detener", points: 0, image: "https://i.giphy.com/media/l4FGDLkDkCnsKwdnq/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "ask", spanish: "preguntar", points: 0, image: "https://i.giphy.com/media/3o6ozoD1ByqYv7ARIk/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "turn", spanish: "girar - dar vueltas -  dar la vuelta", points: 0, image: "https://i.giphy.com/media/ohMtDzrhrWgnK/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "weigh", spanish: "pesar", points: 0, image: "https://i.giphy.com/media/FlOHnTIv1mj2U/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "boil", spanish: "hervir", points: 0, image: "https://i.giphy.com/media/6qhETmXwBIogg/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "remain", spanish: "permanecer - quedarse", points: 0, image: "https://i.giphy.com/media/XEo7YJHUeplXa/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "sigh", spanish: "suspirar - susurrar", points: 0, image: "https://i.giphy.com/media/UUcVHqcMwWMcUoNmSN/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "vacuum", spanish: "aspirar", points: 0, image: "https://i.giphy.com/media/cSw9SQuGRjvr2/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "mind", spanish: "agregar - importar - preocuparse", points: 0, image: "https://i.giphy.com/media/ZCqUyl4FbVYqO3xZBW/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "happen", spanish: "suceder - ocurrir - pasar", points: 0, image: "https://i.giphy.com/media/1lxT4sT6Grek6Ma6mW/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "cry", spanish: "llorar - gritar", points: 0, image: "https://i.giphy.com/media/3o6wrvdHFbwBrUFenu/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "imitate", spanish: "imitar", points: 0, image: "https://i.giphy.com/media/3orifcQSbDdACie0Y8/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "answer", spanish: "contestar - responder", points: 0, image: "https://i.giphy.com/media/3o7aD8WTuPv088JAsg/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "wish", spanish: "desear", points: 0, image: "https://i.giphy.com/media/tpTOw6sljB2U/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "mislay", spanish: "extraviar - perder", points: 0, image: "https://i.giphy.com/media/l41lFw057lAJQMwg0/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "bake", spanish: "hornear", points: 0, image: "https://i.giphy.com/media/EQNWSCCJDIGP8U77c7/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "study", spanish: "estudiar", points: 0, image: "https://i.giphy.com/media/S3Pe5NZqgmE8Tl3NI5/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "absorb", spanish: "absorber", points: 0, image: "https://i.giphy.com/media/3oKHWguzCf0ENuevxS/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "translate", spanish: "traducir", points: 0, image: "https://i.giphy.com/media/3o6vXNQiixBMsf4Dra/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "sew", spanish: "coser", points: 0, image: "https://i.giphy.com/media/8Z5H7TFRdlzIuhPKPy/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "advance", spanish: "avanzar", points: 0, image: "https://i.giphy.com/media/xTiN0GwG6QAh1yjzEs/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "relax", spanish: "relajar - mitigar", points: 0, image: "https://i.giphy.com/media/dCG87dWyRNPEgiLQmm/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "omit", spanish: "omitir", points: 0, image: "https://i.giphy.com/media/26uf2EG78j1paWycw/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "spell", spanish: "deletrear", points: 0, image: "https://i.giphy.com/media/w6LzYFWvgn6RQxKH5M/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "kick", spanish: "patear - dar punta piés", points: 0, image: "https://i.giphy.com/media/Ur7br2RDlMlZQzuwUK/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "plant", spanish: "plantar - sembrar", points: 0, image: "https://i.giphy.com/media/4QFBn7Or4Qw43x6qVs/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "repair", spanish: "reparar - arreglar", points: 0, image: "https://i.giphy.com/media/BcJbdfFSsJPwK4O66J/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "empty", spanish: "vaciar", points: 0, image: "https://i.giphy.com/media/Eqz2BTIm1HWrYftdLD/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "manage", spanish: "manejar - dirigir - arreglárselas", points: 0, image: "https://i.giphy.com/media/p2Ow6zI8NbaCeBnpHV/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "enter", spanish: "entrar", points: 0, image: "https://i.giphy.com/media/KIUU4xdCbIA1D24jLu/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "hate", spanish: "odiar - aborrecer - detestar", points: 0, image: "https://i.giphy.com/media/Ol759kRKsQPn2/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "lick", spanish: "lamer - adular", points: 0, image: "https://i.giphy.com/media/iTtFV9jZbc90YLwwJj/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "touch", spanish: "tocar - rozar", points: 0, image: "https://i.giphy.com/media/109RutRrTGY97a/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "whistle", spanish: "silbar", points: 0, image: "https://i.giphy.com/media/9E5wP1RiPvnos/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "spill", spanish: "derramar -  regar", points: 0, image: "https://i.giphy.com/media/SZQBPO4NqHkh6wmdXk/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "chew", spanish: "masticar", points: 0, image: "https://i.giphy.com/media/da17TWjELQ27RpHXds/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "agree", spanish: "acordar - estar de acuerdo -  acceder", points: 0, image: "https://i.giphy.com/media/jN0ygssTH2hoI/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "bleed", spanish: "sangrar", points: 0, image: "https://i.giphy.com/media/QJtiS9rHFqauLNJ5cP/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "charge", spanish: "cargar", points: 0, image: "https://i.giphy.com/media/MdeSslU80bVsTtWxEh/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "decorate", spanish: "decorar", points: 0, image: "https://i.giphy.com/media/3HBTLptQKeJ3UWGRHr/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "print", spanish: "imprimir", points: 0, image: "https://i.giphy.com/media/l2YOxWj7EddS4AZAQ/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "belong", spanish: "pertenecer", points: 0, image: "https://i.giphy.com/media/otMNPSShc61Tu6qAjQ/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "fasten", spanish: "abrochar", points: 0, image: "https://i.giphy.com/media/BouwBuyFhQwlQYBvmG/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "push", spanish: "empujar", points: 0, image: "https://i.giphy.com/media/h7zqTXl02vFPI9BzFo/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "bother", spanish: "molestar", points: 0, image: "https://i.giphy.com/media/5UH2PJ8VIEuMqN8V6R/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "solve", spanish: "resolver", points: 0, image: "https://i.giphy.com/media/vaKfVsu9zseBy/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "reach", spanish: "alcanzar - llegar", points: 0, image: "https://i.giphy.com/media/t8YPf3ACKeouLzEIvr/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "fear", spanish: "temer", points: 0, image: "https://i.giphy.com/media/PaG51G9OKKdKU/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "appear", spanish: "aparecer", points: 0, image: "https://i.giphy.com/media/Tj56evy9oK11BO7Nfi/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "select", spanish: "seleccionar", points: 0, image: "https://i.giphy.com/media/3oxQNm8SjAqNnnIauA/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "continue", spanish: "continuar", points: 0, image: "https://i.giphy.com/media/rcfSXohU0EzOYuRFrK/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "suppose", spanish: "suponer", points: 0, image: "https://i.giphy.com/media/JwkxjWXEZeqRz5Y4QO/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "camp", spanish: "acampar", points: 0, image: "https://i.giphy.com/media/xUPGclNlLxRs6cVfW0/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "stuff", spanish: "rellenar", points: 0, image: "https://i.giphy.com/media/QvwMDYpAMUm6Q/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "explain", spanish: "explicar", points: 0, image: "https://i.giphy.com/media/fqz9cAi3A7a10WyZpO/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "cheat", spanish: "engañar", points: 0, image: "https://i.giphy.com/media/VGb0I0TSOTnkgwhWQ7/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "receive", spanish: "recibir", points: 0, image: "https://i.giphy.com/media/PgoDdQ1yc2aD4yKIWz/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "fix", spanish: "arreglar", points: 0, image: "https://i.giphy.com/media/WQwQnLNj888eaF2wjd/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "memorize", spanish: "memorizar", points: 0, image: "https://i.giphy.com/media/PlxDRCKKUBUd2v80xq/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "dress", spanish: "vestir", points: 0, image: "https://i.giphy.com/media/2xFvdoHiilA4CKmSuX/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "prepare", spanish: "preparar", points: 0, image: "https://i.giphy.com/media/loAGjMfSUfS7eet5Pw/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "cook", spanish: "cocinar", points: 0, image: "https://i.giphy.com/media/rkgX9MTBXJa1O/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "wrap", spanish: "envolver - empacar", points: 0, image: "https://i.giphy.com/media/NsBdKKJmZC84ZXyXIo/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "identify", spanish: "identificar", points: 0, image: "https://i.giphy.com/media/lqA7hJOmjkg7pKW0sF/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "die", spanish: "morir", points: 0, image: "https://i.giphy.com/media/lDPPhStHv9Jfpem7wI/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "close", spanish: "cerrar", points: 0, image: "https://i.giphy.com/media/WspcNpB89fX1UsMx62/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "stir", spanish: "revolver - remover ", points: 0, image: "https://i.giphy.com/media/l0FsyB60ei0yOm3aXz/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "yawn", spanish: "bostezar", points: 0, image: "https://i.giphy.com/media/d5mI2F3MxCTJu/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "substract", spanish: "sustraer - restar", points: 0, image: "https://i.giphy.com/media/bQuYJcZJEHgpRIWvgt/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "cover", spanish: "cubrir", points: 0, image: "https://i.giphy.com/media/ycHWTWR6yIECvb86P8/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "feed", spanish: "alimentar(se)", points: 0, image: "https://i.giphy.com/media/W5Zf6k7mbnMRWnicfg/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "surround", spanish: "rodear", points: 0, image: "https://i.giphy.com/media/3o6Ztn4kP2LiYLI8Ao/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "publish", spanish: "publicar", points: 0, image: "https://i.giphy.com/media/ofkKkFHe0PQu4/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "persuade", spanish: "persuadir - convencer", points: 0, image: "https://i.giphy.com/media/21I909B1Us5hsGiupn/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "polish", spanish: "pulir", points: 0, image: "https://i.giphy.com/media/xUNd9FS6vqnzQIf9Ze/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "convince", spanish: "convencer", points: 0, image: "https://i.giphy.com/media/lSbF6iuzJP3KvN8hzn/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "drain", spanish: "drenar - escurrir - agotar", points: 0, image: "https://i.giphy.com/media/l2QE73NOoVEoEOkWQ/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "end", spanish: "terminar", points: 0, image: "https://i.giphy.com/media/l4pTjOu0NsrLApt0Q/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "dictate", spanish: "dictar", points: 0, image: "https://i.giphy.com/media/zChwZjBl88KNpdRmA2/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "burn", spanish: "quemar - incendiar", points: 0, image: "https://i.giphy.com/media/r9E1WzdMLUQNscbVTm/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "park", spanish: "parquear - estacionar", points: 0, image: "https://i.giphy.com/media/NfY2xu127irrG/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "mend", spanish: "remendar - reparar", points: 0, image: "https://i.giphy.com/media/BcfWCMgzAvrX8qvOmJ/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "expect", spanish: "esperar", points: 0, image: "https://i.giphy.com/media/xT9IgnxYv1zOoxxBTi/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "borrow", spanish: "pedir prestado", points: 0, image: "https://i.giphy.com/media/11zyJuJXMxxJFm/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "represent", spanish: "representar", points: 0, image: "https://i.giphy.com/media/j1XURZ9p4HjaMRdywD/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "scrub", spanish: "fregar -  restregar", points: 0, image: "https://i.giphy.com/media/B1jBJkaYQgaDAsEiZX/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "smoke", spanish: "fumar", points: 0, image: "https://i.giphy.com/media/14qIliCMe87BwA/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "hurry", spanish: "apresurar(se)", points: 0, image: "https://i.giphy.com/media/QVs6OmwbbGvWPJJ75m/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "smell", spanish: "oler - husmear", points: 0, image: "https://i.giphy.com/media/3oEjHXnhx3x2iA5lQY/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "brown", spanish: "tostar", points: 0, image: "https://i.giphy.com/media/QZ8H1uQfTeumErP3sk/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "dust", spanish: "desempolvar", points: 0, image: "https://i.giphy.com/media/3o7buh0sx5p7qrnJ5u/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "miss", spanish: "echar de menos -  perder", points: 0, image: "https://i.giphy.com/media/mOdkhvtXTnnYXjCCZL/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "drop", spanish: "bajar - soltar", points: 0, image: "https://i.giphy.com/media/mD44ZStfDEDngsTL6g/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "slice", spanish: "rebanar", points: 0, image: "https://i.giphy.com/media/l0MYJLrv6NmQx3Eoo/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "fail", spanish: "fallar - fracasar - perder", points: 0, image: "https://i.giphy.com/media/KvTuvZjYiERHy/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "broil", spanish: "asar", points: 0, image: "https://i.giphy.com/media/DC3KWIx4iQXf1ga9o7/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "land", spanish: "aterrizar - desembarcar", points: 0, image: "https://i.giphy.com/media/sDn8Wv2gIDDl3B99d2/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "trust", spanish: "confiar - creer", points: 0, image: "https://i.giphy.com/media/ZzScEDPMnJFp6/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "pick up", spanish: "recoger", points: 0, image: "https://i.giphy.com/media/bocdFeJKj8axPinbsD/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "try", spanish: "probar - intentar - ensayar - tratar", points: 0, image: "https://i.giphy.com/media/8NNDrB5KakH1m/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "rain", spanish: "llover", points: 0, image: "https://i.giphy.com/media/3og0IOUWB5AZoP6la0/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "clean", spanish: "limpiar", points: 0, image: "https://i.giphy.com/media/NHHYRm7mAUQ6Y/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "wave", spanish: "agitar - ondear", points: 0, image: "https://i.giphy.com/media/y9BPgWuDnkKqE5NvwK/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "call", spanish: "llamar", points: 0, image: "https://i.giphy.com/media/VDe02J11N1I7swdREG/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "pass", spanish: "pasar - aprobar - superar", points: 0, image: "https://i.giphy.com/media/l0MYu0z6TH0t4PFII/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "shed", spanish: "quitarse - despojarse", points: 0, image: "https://i.giphy.com/media/jrhSVtLxOKoNEUUTs0/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "imagine", spanish: "imaginar", points: 0, image: "https://i.giphy.com/media/l2JdX9FBRJDg0sdTq/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "depend", spanish: "depender", points: 0, image: "https://i.giphy.com/media/l4pTpbGbC59BbFfSE/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "comment", spanish: "comentar", points: 0, image: "https://i.giphy.com/media/fngcM35fl2ySrblJLV/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "collect", spanish: "coleccionar", points: 0, image: "https://i.giphy.com/media/3o6Mb5mDb7raqYERZC/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "finish", spanish: "acabar(con) -  terminar", points: 0, image: "https://i.giphy.com/media/VQ77RNKX0nyaA/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "cross", spanish: "cruzar - atravesar", points: 0, image: "https://i.giphy.com/media/3oxRmD9a5pLTOOLigM/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "arrive", spanish: "llegar", points: 0, image: "https://i.giphy.com/media/3orif1gluXOV1jIPWU/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "settle", spanish: "resolver - llegar a un acuerdo", points: 0, image: "https://i.giphy.com/media/XnRQH9K6KDqotoQgXe/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "breed", spanish: "criar - educar", points: 0, image: "https://i.giphy.com/media/noHdhIkGHcIhy/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "declare", spanish: "declarar", points: 0, image: "https://i.giphy.com/media/GoqONiCOBhVDRwXxvU/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "erase", spanish: "borrar", points: 0, image: "https://i.giphy.com/media/KD7Ud1YX1nYRkb2r29/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "sneeze", spanish: "estornudar", points: 0, image: "https://i.giphy.com/media/xTk9ZP6AM0EKyQwqNW/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "multiply", spanish: "multiplicar", points: 0, image: "https://i.giphy.com/media/XcFqv8EzBiAlzeEID9/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "live", spanish: "vivir", points: 0, image: "https://i.giphy.com/media/KTqACPHWbIPTLFzgNM/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "change", spanish: "cambiar", points: 0, image: "https://i.giphy.com/media/KcKtC7mz4EHJJPgaXp/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "save", spanish: "guardar - ahorrar - salvar", points: 0, image: "https://i.giphy.com/media/mv2oHmVjhdOK6LFRZX/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "flunk", spanish: "fracasar - reprobar", points: 0, image: "https://i.giphy.com/media/3orieO2nOMDh5kqBoc/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "promise", spanish: "prometer", points: 0, image: "https://i.giphy.com/media/Cu7tfLe1edy3HE7JfC/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "start", spanish: "agregar - comenzar - empezar - iniciar", points: 0, image: "https://i.giphy.com/media/xTiTnmeJ1bBGONMCBy/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "repeat", spanish: "repetir", points: 0, image: "https://i.giphy.com/media/dzvcOaG7QsRd6/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "invite", spanish: "invitar", points: 0, image: "https://i.giphy.com/media/9ses36mVQaH2XBD8Om/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "want", spanish: "querer - desear - necesitar", points: 0, image: "https://i.giphy.com/media/VpGJZP4KlNRQc/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "fry", spanish: "freir(se)", points: 0, image: "https://i.giphy.com/media/41xmKVhZI4Ymfr2rhT/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "need", spanish: "necesitar - requerir", points: 0, image: "https://i.giphy.com/media/nh9k1qzeLf99S/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "care", spanish: "cuidar", points: 0, image: "https://i.giphy.com/media/PCyJu30x3XTIRHyivT/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "brush", spanish: "cepillar", points: 0, image: "https://i.giphy.com/media/dcl7xz9f5RhSw/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "kill", spanish: "matar - acabar con", points: 0, image: "https://i.giphy.com/media/QX26hw37ZXORAWNxyC/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "complain", spanish: "quejarse", points: 0, image: "https://i.giphy.com/media/5uFu5NilveRQ8jBBU2/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "wonder", spanish: "preguntarse - asombrarse - maravillarse", points: 0, image: "https://i.giphy.com/media/872o15eAXFBw66UfNl/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "skate", spanish: "patinar", points: 0, image: "https://i.giphy.com/media/3o6gDYNNm8a2hfzTNe/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "bathe", spanish: "bañar", points: 0, image: "https://i.giphy.com/media/huvuSTprdx9BiBmNYe/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "walk", spanish: "caminar - andar - pasear - andar", points: 0, image: "https://i.giphy.com/media/omHPYZttAVAAw/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "travel", spanish: "viajar - andar - recorrer", points: 0, image: "https://i.giphy.com/media/AErExHJVxRbkm5hPkB/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "sound", spanish: "sonar - tocar", points: 0, image: "https://i.giphy.com/media/JxYcC04MT2Noc/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "shop", spanish: "comprar (de tiendas)", points: 0, image: "https://i.giphy.com/media/3ohs83bO7MKV9koZuE/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "permit", spanish: "permitir", points: 0, image: "https://i.giphy.com/media/tIeCLkB8geYtW/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "occur", spanish: "ocurrir - suceder", points: 0, image: "https://i.giphy.com/media/e3aUKF8Vidrag/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "clothe", spanish: "vestir - arropar", points: 0, image: "https://i.giphy.com/media/1AubIMDoGjnsk/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "fit", spanish: "caber - encajar - ajustar", points: 0, image: "https://i.giphy.com/media/l2Je6sbvJEn1W9OWQ/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "jump", spanish: "saltar - brincar", points: 0, image: "https://i.giphy.com/media/l0HlMhcc67eLP7oeA/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "name", spanish: "nombrar - denominar", points: 0, image: "https://i.giphy.com/media/QWigz8zGygObKfShkF/200w.webp", current_review: Date.now(), next_review: Date.now() },
            ]
        },
        {
            _id: '2',
            name: 'Partes del Cuerpo',
            icon: '🫀',
            words: [
                { english: "hair", spanish: "cabello", points: 0, image: "https://i.giphy.com/media/1wpxKyKAONy98ZhP9G/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "head", spanish: "cabeza", points: 0, image: "https://i.giphy.com/media/NKSq1x79SPTGg/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "face", spanish: "rostro", points: 0, image: "https://i.giphy.com/media/xT1XGyIsUvJNwWfShy/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "forehead", spanish: "frente", points: 0, image: "https://i.giphy.com/media/zb8B5tlJjdpzW/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "ears", spanish: "orejas", points: 0, image: "https://i.giphy.com/media/l4pT6w42S93xNKz2U/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "eyebrows", spanish: "cejas", points: 0, image: "https://i.giphy.com/media/1hA34Uzt3aScCLsZgF/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "eyelashes", spanish: "pestañas", points: 0, image: "https://i.giphy.com/media/bxc12JagLEzrW/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "eyes", spanish: "ojos", points: 0, image: "https://i.giphy.com/media/GQI382aMVej0k/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "nose", spanish: "nariz", points: 0, image: "https://i.giphy.com/media/MNvN8IOC2xd8L5TCNM/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "mustache", spanish: "bigote", points: 0, image: "https://i.giphy.com/media/qSiYwYUlhE5fq/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "mouth", spanish: "boca", points: 0, image: "https://i.giphy.com/media/Lq0h93752f6J9tijrh/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "lips", spanish: "labios", points: 0, image: "https://i.giphy.com/media/jOFIKFiMOz9V6/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "tongue", spanish: "lengua", points: 0, image: "https://i.giphy.com/media/BofJb4WxJnz7jFfxeD/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "teeth", spanish: "dientes", points: 0, image: "https://i.giphy.com/media/l3diGzJhCTx3Ngure/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "tooth", spanish: "diente", points: 0, image: "https://i.giphy.com/media/l3DdGwSucoEG5VNVC/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "cheeks", spanish: "mejillas", points: 0, image: "https://i.giphy.com/media/H1Gd8UC0GjXRUeo6wc/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "freckles", spanish: "pecas", points: 0, image: "https://i.giphy.com/media/LP4TvzUUzZ07LDi4sh/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "chin", spanish: "barbilla", points: 0, image: "https://i.giphy.com/media/1QfiXem2iEi7COEMWt/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "beard", spanish: "barba", points: 0, image: "https://i.giphy.com/media/5ae3ZNBFIwSjK/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "neck", spanish: "cuello", points: 0, image: "https://i.giphy.com/media/UVDF28ep8NJF6/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "shoulders", spanish: "hombros", points: 0, image: "https://i.giphy.com/media/xUA7b0Jb2dIt1NA9jO/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "armpit", spanish: "axila", points: 0, image: "https://i.giphy.com/media/QZ2J1kIdxsGYnR9ska/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "chest", spanish: "pecho", points: 0, image: "https://i.giphy.com/media/xT1XGBVtbsa23KhSb6/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "breasts", spanish: "senos", points: 0, image: "https://i.giphy.com/media/gQ2fLEOtl4F5m/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "abdomen", spanish: "abdomen", points: 0, image: "https://i.giphy.com/media/l1ugn5yDMJDNfmJZC/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "belly", spanish: "vientre", points: 0, image: "https://i.giphy.com/media/zUW23b6FmzB5e/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "hips", spanish: "cadera", points: 0, image: "https://i.giphy.com/media/3bqSbktO7KcQU/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "waist", spanish: "cintura", points: 0, image: "https://i.giphy.com/media/WhoNNhPTSgNkA/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "belly button", spanish: "ombligo", points: 0, image: "https://i.giphy.com/media/3oKHWkwJK8Ibu490xa/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "back", spanish: "espalda", points: 0, image: "https://i.giphy.com/media/mqjnXsqlSmrFJDjpNM/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "buttocks", spanish: "glúteos", points: 0, image: "https://i.giphy.com/media/YP74iVhXjrZmWPqb6d/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "arms", spanish: "brazos", points: 0, image: "https://i.giphy.com/media/jQbKNjpx4r5cxqEuPb/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "elbow", spanish: "codo", points: 0, image: "https://i.giphy.com/media/e3WzjGpaanMm4/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "forearm", spanish: "antebrazo", points: 0, image: "https://i.giphy.com/media/cZDmWv5SjMdZwhMf1M/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "wrist", spanish: "muñeca", points: 0, image: "https://i.giphy.com/media/gq9SPDGxZtxaI7kQnO/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "fist", spanish: "puño", points: 0, image: "https://i.giphy.com/media/WoF3yfYupTt8mHc7va/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "hand", spanish: "mano", points: 0, image: "https://i.giphy.com/media/UQVIhXZpCS17U3U4xR/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "fingers", spanish: "dedos", points: 0, image: "https://i.giphy.com/media/3o72EUwmrRFtyT1Vhm/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "knuckles", spanish: "nudillos", points: 0, image: "https://i.giphy.com/media/4ttCTXSeAu0GSXy9h5/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "nails", spanish: "uñas", points: 0, image: "https://i.giphy.com/media/l8OrHJlaGTEsM/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "legs", spanish: "piernas", points: 0, image: "https://i.giphy.com/media/KxYYj1sXfvve8/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "thigh", spanish: "muslo", points: 0, image: "https://i.giphy.com/media/X0iEaPoda9Ps2nhbgO/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "knees", spanish: "rodillas", points: 0, image: "https://i.giphy.com/media/l2JejHs0YIAUpcAWQ/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "foot", spanish: "pie", points: 0, image: "https://i.giphy.com/media/loHIRKRjn6Nu2Xixbw/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "feet", spanish: "pies", points: 0, image: "https://i.giphy.com/media/3o7WIucW89bVVGgsIE/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "ankle", spanish: "tobillo", points: 0, image: "https://i.giphy.com/media/5AwCyyagCgqX77tsyK4/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "heel", spanish: "talón", points: 0, image: "https://i.giphy.com/media/FWTbmJb6SG55C/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "skull", spanish: "cráneo", points: 0, image: "https://i.giphy.com/media/r1L9IlkeMbKoyJrMtm/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "brain", spanish: "cerebro", points: 0, image: "https://i.giphy.com/media/l41m04gr7tRet7Uas/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "throat", spanish: "garganta", points: 0, image: "https://i.giphy.com/media/U7LqpyMWtoeSXayium/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "ribs", spanish: "costillas", points: 0, image: "https://i.giphy.com/media/3o6Zt6FgqP2HYRJ47m/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "heart", spanish: "corazón", points: 0, image: "https://i.giphy.com/media/ZOStzpF9H5syI/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "lungs", spanish: "pulmones", points: 0, image: "https://i.giphy.com/media/YImJMKZwMYsOk/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "stomach", spanish: "estómago", points: 0, image: "https://i.giphy.com/media/9C2hzbt5VUnJ85ldZ0/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "blood", spanish: "sangre", points: 0, image: "https://i.giphy.com/media/UGGe8BBrkuAUM/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "bones", spanish: "huesos", points: 0, image: "https://i.giphy.com/media/14p7smEhLwMHD2/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "muscles", spanish: "músculos", points: 0, image: "https://i.giphy.com/media/BCIoXfA95d1ba/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "skeleton", spanish: "esqueleto", points: 0, image: "https://i.giphy.com/media/3ohhwfAa9rbXaZe86c/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "skin", spanish: "piel", points: 0, image: "https://i.giphy.com/media/9AXvu1JYGPrSU/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "veins", spanish: "venas", points: 0, image: "https://i.giphy.com/media/8qrmcwwJnW5XaLJQUB/200w.webp", current_review: Date.now(), next_review: Date.now() }
            ]
        },
        {
            _id: '3',
            name: 'WH Questions',
            icon: '❓',
            words: [
                { english: "who", spanish: "¿Quién?", points: 0, image: "https://i.giphy.com/media/xT9DPsaooCwWMHyydO/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "what", spanish: "¿Qué ?", points: 0, image: "https://i.giphy.com/media/iFxaWHoUsXqm6ej3zp/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "what", spanish: "¿Cuál? (opciones desconocidas)", points: 0, image: "https://i.giphy.com/media/iFxaWHoUsXqm6ej3zp/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "when", spanish: "¿Cuándo?", points: 0, image: "https://i.giphy.com/media/fUwOs80ja3sTPpjndh/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "why", spanish: "¿Por qué?", points: 0, image: "https://i.giphy.com/media/5BWVeEbJsaB4UZAzSz/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "where", spanish: "¿Dónde?", points: 0, image: "https://i.giphy.com/media/26ni7e85ldigoAvK0/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "whose", spanish: "¿De quién?", points: 0, image: "https://i.giphy.com/media/3o7bu1Q2WGULpXCUNy/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "which", spanish: "¿Cuál? (opciones conocidas)", points: 0, image: "https://i.giphy.com/media/lx7AtejahSmgIWmLX5/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "how", spanish: "¿Cómo?", points: 0, image: "https://i.giphy.com/media/26mkhPIN0KxjxfPbi/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "how old", spanish: "¿Qué edad?", points: 0, image: "https://i.giphy.com/media/VO1qsPmPvwLmhxNalE/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "how often", spanish: "¿Con qué frecuencia?", points: 0, image: "https://i.giphy.com/media/xT5LMVwj6YcQarnVPa/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "how fast", spanish: "¿Qué tan rapido?", points: 0, image: "https://i.giphy.com/media/KKBpCeK0ASoPS/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "how long", spanish: "¿Cuánto tiempo?", points: 0, image: "https://i.giphy.com/media/GJpJJPfhcoDl0xOZXI/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "how many", spanish: "¿Cuántos(as)? (contable)", points: 0, image: "https://i.giphy.com/media/j5ra3QdLthGSPtjmqz/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "how much", spanish: "¿Cuántos(as)? (incontable)", points: 0, image: "https://i.giphy.com/media/LScY2HbrHCICWKrUbO/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "how well", spanish: "¿Qué tan bien?", points: 0, image: "https://i.giphy.com/media/JkiqsyCzZmRLqBuwJ8/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "how tall", spanish: "¿Cuánto mide?", points: 0, image: "https://i.giphy.com/media/ZeF8zmEwCKH1F8qN9O/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "how far", spanish: "¿Qué tan lejos?", points: 0, image: "https://i.giphy.com/media/xnsFqNS2g4NIzKbM58/200w.webp", current_review: Date.now(), next_review: Date.now() }
            ]
        },
        {
            _id: '4',
            name: 'Verbos Irregulares',
            icon: '💥',
            words: [
                { english: "rise, rose, risen", spanish: "subir - ascender", points: 0, image: " https://i.giphy.com/media/kKkxK0OAb8kLrEtLew/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "flee, fled, fled", spanish: "evitar - huir de", points: 0, image: " https://i.giphy.com/media/S3PjeN6iPYyxJYvdji/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "befall, befell, befallen", spanish: "suceder - acontecer - ocurrir", points: 0, image: " https://i.giphy.com/media/eg40fWsnGDKSwzZ9JM/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "wear, wore, worn", spanish: "usar - llevar puesto", points: 0, image: " https://i.giphy.com/media/sMTz9zCVqkzU4/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "put, put, put", spanish: "poner - colocar", points: 0, image: " https://i.giphy.com/media/26tk0bT7b5j9eihyg/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "bid, bid, bid", spanish: "mandar - ordenar", points: 0, image: " https://i.giphy.com/media/clnMyAMF1Enzf3Mrh2/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "grind, ground, ground", spanish: "moler - triturar", points: 0, image: " https://i.giphy.com/media/Ie3nZAD9A6fOe47mum/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "split, split, split", spanish: "dividirse - partir", points: 0, image: " https://i.giphy.com/media/O1I2B29viaEhuWT01R/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "send, sent, sent", spanish: "enviar - mandar", points: 0, image: " https://i.giphy.com/media/1BgqNZwAfxiiMN3vsT/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "go, went, gone", spanish: "ir", points: 0, image: " https://i.giphy.com/media/69zJi6jaJtYpRHZwd6/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "lend, lent, lent", spanish: "prestar", points: 0, image: " https://i.giphy.com/media/MdjqowHpLJpVXUApMk/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "seek, sought, sought", spanish: "buscar - solicitar", points: 0, image: " https://i.giphy.com/media/mJ7C6QzV9UwVf0bkzr/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "light, lit, lit", spanish: "encender - prender", points: 0, image: " https://i.giphy.com/media/l2JebisijdzVL2Cqs/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "speed, sped, sped", spanish: "acelerar - apresurarse - darse prisa", points: 0, image: " https://i.giphy.com/media/qxM03tz9rg4RYThmkG/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "swear, swore, sworn", spanish: "jurar", points: 0, image: " https://i.giphy.com/media/5t2ev2eCEzYWjag91c/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "tell, told, told", spanish: "decir - contar", points: 0, image: " https://i.giphy.com/media/3ohhwrd3CjE7A8otzi/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "quit, quit, quit", spanish: "dejar-abandonar", points: 0, image: " https://i.giphy.com/media/HIyGDBxdiQ5uJYTGbP/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "breed, bred, bred", spanish: "criar - educar", points: 0, image: " https://i.giphy.com/media/noHdhIkGHcIhy/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "feed, fed, fed", spanish: "alimentar(se)", points: 0, image: " https://i.giphy.com/media/W5Zf6k7mbnMRWnicfg/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "burn, burnt/burned, burnt/burned", spanish: "quemar - incendiar", points: 0, image: " https://i.giphy.com/media/r9E1WzdMLUQNscbVTm/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "deal, dealt, dealt", spanish: "negociar - comerciar", points: 0, image: " https://i.giphy.com/media/ojwMVxGqy4oRO4c8rw/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "creep, crept, crept", spanish: "arrastrarse - deslizarse - gatear", points: 0, image: " https://i.giphy.com/media/26Ffci1HvhUK5gVLG/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "let, let, let", spanish: "dejar - permitir", points: 0, image: " https://i.giphy.com/media/m6Zf7BamTPRcI/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "bleed, bled, bled", spanish: "sangrar", points: 0, image: " https://i.giphy.com/media/QJtiS9rHFqauLNJ5cP/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "hang, hung, hung", spanish: "colgar - suspender", points: 0, image: " https://i.giphy.com/media/cNeuWYGCJfRdS9j89F/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "cut, cut, cut", spanish: "cortar - recortar", points: 0, image: " https://i.giphy.com/media/eKasUvPB01V4TFH2YA/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "flee, fled, fled", spanish: "evitar - huir de", points: 0, image: " https://i.giphy.com/media/S3PjeN6iPYyxJYvdji/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "behold, beheld, beheld", spanish: "contemplar - mirar", points: 0, image: " https://i.giphy.com/media/3oKIPvcLVLEnbTAqEU/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "teach, taught, taught", spanish: "enseñar", points: 0, image: " https://i.giphy.com/media/l0MYLE9bob7mhosfu/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "lead, led, led", spanish: "conducir - liderar", points: 0, image: " https://i.giphy.com/media/3orif4BtRvTgRedJF6/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "shoot, shot, shot", spanish: "tirar - disparar", points: 0, image: " https://i.giphy.com/media/VEzspneHDuo4PQzKc3/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "sleep, slept, slept", spanish: "dormir", points: 0, image: " https://i.giphy.com/media/kIRicSBQwa23pYExQT/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "feel, felt, felt", spanish: "sentir", points: 0, image: " https://i.giphy.com/media/JRJzW4LosT4CoRa0TZ/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "fling, flung, flung", spanish: "arrojar - lanzar - tirar", points: 0, image: " https://i.giphy.com/media/T2b7Jnt7rB9Li/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "swim, swam, swum", spanish: "nadar", points: 0, image: " https://i.giphy.com/media/l3V0mnnGcVblF8bAI/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "string, strungs, strung", spanish: "atar(cordones)", points: 0, image: " https://i.giphy.com/media/j6MMHvVSIAzhAiP2IZ/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "slide, slid, slid", spanish: "resbalar(se)", points: 0, image: " https://i.giphy.com/media/3otPoOT462O0kTx5RK/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "find, found, found", spanish: "encontrar - hallar", points: 0, image: " https://i.giphy.com/media/zmlCPKMlXwq6k/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "forbid, forbade, forbidden", spanish: "prohibir - privar", points: 0, image: " https://i.giphy.com/media/Ch3UBdp7uI8to76zVl/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "ride, rode, ridden", spanish: "cabalgar - montar", points: 0, image: " https://i.giphy.com/media/naXyAp2VYMR4k/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "freeze, froze, frozen", spanish: "congelar - helar", points: 0, image: " https://i.giphy.com/media/d3mlmtNPoxNrt4Bi/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "beat, beat, beaten", spanish: "vencer - batir", points: 0, image: " https://i.giphy.com/media/l3vRg3PXSVON7Rogo/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "run, ran, run", spanish: "correr", points: 0, image: " https://i.giphy.com/media/3o7ZetIsjtbkgNE1I4/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "cling, clung, clung", spanish: "agarrar - aferrarse - adherirse", points: 0, image: " https://i.giphy.com/media/2zoLgckxd9FxDgx6gD/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "swing, swung, swung", spanish: "balancearse - girar - columpiarse", points: 0, image: " https://i.giphy.com/media/Kuw5gir5rTnaw/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "bring, brought, brought", spanish: "traer - llevar", points: 0, image: " https://i.giphy.com/media/0XQYtbNg4JXibQWY9e/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "tear, tore, torn", spanish: "rasgar - desgarrar - arrancar", points: 0, image: " https://i.giphy.com/media/3JOy7A3NxiCZUqJo9c/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "make, made, made", spanish: "hacer - fabricar", points: 0, image: " https://i.giphy.com/media/34RQ5J9TJT6mc8WBi2/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "choose, chose, chosen", spanish: "escoger - elegir - optar", points: 0, image: " https://i.giphy.com/media/3oipPTHYlTpCw8oBBy/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "upset, upset, upset", spanish: "alterar - perturbar", points: 0, image: " https://i.giphy.com/media/GnqgAJvlpkK76/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "read, read, read", spanish: "leer", points: 0, image: "https://i.giphy.com/media/8dYmJ6Buo3lYY/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "stand, stood, stood", spanish: "ponerse de pie - pararse", points: 0, image: "https://i.giphy.com/media/j6volCQRaACpo5h4EM/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "spin, spun, spun", spanish: "hacer girar (vueltas)", points: 0, image: "https://i.giphy.com/media/bXvwCQglnTGKs/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "leave, left, left", spanish: "salir - abandonar", points: 0, image: "https://i.giphy.com/media/48FhEMYGWji8/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "strive, strove, striven", spanish: "esforzarse", points: 0, image: "https://i.giphy.com/media/XiPg4fGi4RMPTJnFUF/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "dig, dug, dug", spanish: "cavar - excavar", points: 0, image: "https://i.giphy.com/media/12bpEjD05ac2IM/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "blow, blew, blown", spanish: "soplar - ventear", points: 0, image: "https://i.giphy.com/media/yoJC2P9fUkIm7lDMeA/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "eat, ate, eaten", spanish: "comer", points: 0, image: "https://i.giphy.com/media/3osxY7eI6enqNBo2mQ/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "win, won, won", spanish: "ganar", points: 0, image: "https://i.giphy.com/media/3ohs4su16JU4XsVKfe/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "awake, awoke, awoke", spanish: "despertar(se)", points: 0, image: "https://i.giphy.com/media/FtPS6kvzFEiApsLisX/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "abide, abode, abode", spanish: "morar - habitar - tolerar", points: 0, image: "https://i.giphy.com/media/ni2wk9VTYMw9O/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "strike, struck, struck", spanish: "golpear - pegar", points: 0, image: "https://i.giphy.com/media/1YaJqvpJKkASs4f6ic/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "weave, wove, woven", spanish: "tejer", points: 0, image: "https://i.giphy.com/media/bltiqBEjFQlaTnxd6C/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "forecast, forecast, forecast", spanish: "pronosticar", points: 0, image: "https://i.giphy.com/media/tja7MJ6DYOenIR4oDc/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "spread, spread, spread", spanish: "extender - untar", points: 0, image: "https://i.giphy.com/media/Jfu3UlHpJK1Hi/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "stink, stank, stunk", spanish: "apestar - oler mal", points: 0, image: "https://i.giphy.com/media/TIWrHYuuOKc3j90Ylm/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "say, said, said", spanish: "decir", points: 0, image: "https://i.giphy.com/media/U4NM7UyhnF5Pa/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "forgive, forgave, forgiven", spanish: "perdonar", points: 0, image: "https://i.giphy.com/media/lpIqwGHhwmsNyAyrvy/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "spring, sprang, sprung", spanish: "saltar - brotar", points: 0, image: "https://i.giphy.com/media/R9dVdx76BJFks/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "see, saw, seen", spanish: "ver", points: 0, image: "https://i.giphy.com/media/cP6G0uiTHCzMUdrdS1/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "hit, hit, hit", spanish: "golpear - pegar", points: 0, image: "https://i.giphy.com/media/qIfG2193qAwGgw4hdg/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "sign, signed, signed", spanish: "firmar", points: 0, image: "https://i.giphy.com/media/l2JegHKlrPqqOjjig/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "spit, spit, spit", spanish: "escupir", points: 0, image: "https://i.giphy.com/media/l0HU5bbgdW6qzJsmQ/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "overcome, overcame, overcome", spanish: "superar - triunfar", points: 0, image: "https://i.giphy.com/media/1Xd9JPDm9CAaRe66oP/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "buy, bought, bought", spanish: "comprar - adquirir", points: 0, image: "https://i.giphy.com/media/sDcfxFDozb3bO/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "lose, lost, lost", spanish: "perder", points: 0, image: "https://i.giphy.com/media/UNNffDUqDJYs/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "hurt, hurt, hurt", spanish: "herir - lastimar", points: 0, image: "https://i.giphy.com/media/13w5HmyiuaZ224/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "forget, forgot, forgotten", spanish: "olvidar", points: 0, image: "https://i.giphy.com/media/3ohhwoBqhih33ck000/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "mistake, mistook, mistaken", spanish: "equivocarse", points: 0, image: "https://i.giphy.com/media/3ohhwvAprUeTXBQxXy/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "wake, woke, woken", spanish: "despertar(se)", points: 0, image: "https://i.giphy.com/media/WZj3l2HIRubde/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "bear, bore, born", spanish: "soportar - aguantar", points: 0, image: "https://i.giphy.com/media/Ie4CIIvQS0bk3zwZlM/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "fall, fell, fallen", spanish: "caer(se)", points: 0, image: "https://i.giphy.com/media/3oxRmGNqKwCzJ0AwPC/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "cast, cast, cast", spanish: "moldear - repartir - echar - tirar", points: 0, image: "https://i.giphy.com/media/iFDKydfCn7PTZePMto/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "drive, drove, driven", spanish: "manejar - conducir", points: 0, image: "https://i.giphy.com/media/4V2QpkTTYtr7us3iKM/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "lay, laid, laid", spanish: "poner - colocar - echar", points: 0, image: "https://i.giphy.com/media/3o7WIN1WaLva5ORmfK/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "shrink, shrank, shrunk", spanish: "encoger - contraer", points: 0, image: "https://i.giphy.com/media/5Yv6KywEdxUU4EjC1c/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "hear, heard, heard", spanish: "oir", points: 0, image: "https://i.giphy.com/media/rhgwg4qBu97ISgbfni/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "show, showed, shown", spanish: "mostrar - enseñar", points: 0, image: "https://i.giphy.com/media/10lib5POdEnKFO/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "wring, wrung, wrung", spanish: "escurrir - retorcer", points: 0, image: "https://i.giphy.com/media/xdOspsxc8rWYE/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "take, took, taken", spanish: "tomar - agarrar - coger", points: 0, image: "https://i.giphy.com/media/7JKTwn0tBu3ecZZQzx/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "fly, flew, flown", spanish: "volar - huir", points: 0, image: "https://i.giphy.com/media/gZEBpuOkPuydi/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "give, gave, given", spanish: "dar - regalar", points: 0, image: "https://i.giphy.com/media/PPEDuq1xCAf8sj75yw/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "wind, wound, wound", spanish: "enrollar", points: 0, image: "https://i.giphy.com/media/5p0M9XGpSff1cniSEj/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "keep, kept, kept", spanish: "mantener - guardar", points: 0, image: "https://i.giphy.com/media/LUBNhsWA67Saqv2uQe/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "spend, spend, spent", spanish: "gastar - pasar el tiempo", points: 0, image: "https://i.giphy.com/media/d3mmdNnW5hkoUxTG/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "fight, fought, fought", spanish: "pelear - luchar", points: 0, image: "https://i.giphy.com/media/3ohc0QQkTH6YK8g4zS/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "thrust, thrust, thrust", spanish: "clavar - empujar", points: 0, image: "https://i.giphy.com/media/8Z5xJbiqa2hS25nweC/200w.webp", current_review: Date.now(), next_review: Date.now() },
                { english: "rid, rid, rid", spanish: "librarse de - deshacerse", points: 0, image: "https://i.giphy.com/media/3ohzdGCQtxtZkqpBdK/200w.webp", current_review: Date.now(), next_review: Date.now() },
            ]
        }
    ]
}